version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sanamed_db_container
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: postsanamed  # Aquí cambiamos el nombre de la BD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  pgdata:
